version: '2'
services:
  kafka-base:
    build:
      context: .
      dockerfile: Dockerfile.openJDK
    image: kafka-base
  kafka-zookeeper:
    image: kafka-base
    container_name: kafka-zookeeper
    command: ./bin/zookeeper-server-start.sh config/zookeeper.properties
    ports:
     - "2181:2181"
    depends_on:
      - "kafka-base"
  kafka-broker:
    image: kafka-base
    container_name: kafka-broker
    command: ./bin/kafka-server-start.sh config/server.properties --override zookeeper.connect=kafka-zookeeper:2181 --override listeners=PLAINTEXT://0.0.0.0:9092
    ports:
     - "9092:9092"
    depends_on:
     - "kafka-zookeeper"
