FROM openjdk:8-jre-alpine
ENV ZOOKEEPER zookeeper
RUN apk add --no-cache curl bash && curl http://mirror.netinch.com/pub/apache/kafka/0.10.2.1/kafka_2.12-0.10.2.1.tgz | tar -xvz -C /var/opt
WORKDIR /var/opt/kafka_2.12-0.10.2.1
CMD ["sh", "-c", "./bin/kafka-server-start.sh config/server.properties --override zookeeper.connect=${ZOOKEEPER}:2181 --override listeners=PLAINTEXT://0.0.0.0:9092"]
