FROM openjdk:8-jre-alpine
RUN apk add --no-cache curl bash && curl http://mirror.netinch.com/pub/apache/kafka/0.10.2.1/kafka_2.12-0.10.2.1.tgz | tar -xvz -C /var/opt
WORKDIR /var/opt/kafka_2.12-0.10.2.1
CMD ["sh", "-c", "/var/opt/kafka_2.12-0.10.2.1/bin/zookeeper-server-start.sh config/zookeeper.properties"]
